Repository GSG-G11/Analytica-Team-One, pull requests merged in 2022-02, with the labels that each got.

#3 Create Folder Structure
  assets/css/style.css
  assets/js/data.js
  assets/js/dom.js
  assets/js/logic.js
  assets/js/logic.test.js
  cart/cart.css
  cart/cart.html
  index.html
  seller/seller.css
  seller/seller.html
Labels: Awaiting Review

#5 create npm and jest package
  .gitignore
  package-lock.json
  package.json
Labels: Done

#9 Add basic content to index.html and style
  assets/css/style.css
  index.html
Labels: Done

#15 entry data to file data.js
  .vscode/settings.json
  assets/js/data.js
  seller/seller.css
  seller/seller.html
Labels: Done

#16 Created products section and product cards
  assets/css/style.css
  index.html
Labels: Done

#17 add form to add product
  seller/seller.css
  seller/seller.html
Labels: Done

#19 14 create footer in index.html
  assets/css/style.css
  index.html
Labels: Done

#21 create navbar,hero section and create img folder
  assets/css/style.css
  img/Laptop.png
  img/logo.png
  index.html
Labels: Awaiting Review

#24 Final homepage touches
  assets/css/style.css
  index.html
Labels: Awaiting Review

#29 add nav and footer to seller page
  assets/css/style.css
  index.html
  seller/seller.css
  seller/seller.html
Labels: Awaiting Review

#28 Add home icon in homepage
  assets/css/style.css
  index.html
Labels: Awaiting Review

#30 ad background to form
  seller/seller.css
  seller/seller.html
Labels: Awaiting Review

#31 Final touch on hero section
  assets/css/style.css
  index.html
Labels: Awaiting Review

#38 add validation to form add product
  seller/seller.html
Labels: Awaiting Review

#40 Rendered Data from Data.js into homepage
  assets/js/data.js
  assets/js/dom.js
  index.html
Labels: Awaiting Review

#42 Filter by price or category
  assets/js/dom.js
  index.html
Labels: Awaiting Review

#43 add new product to the arrey
  assets/js/data.js
  seller/seller.html
  seller/seller.js
Labels: Done

#46 Add Search function and seperate files of logic, dom and test
  assets/js/dom.js
  assets/js/logic.js
  assets/js/logic.test.js
  package.json
Labels: Awaiting Review

#45 finishing of creating delete items from my cart
  assets/js/cart.js
Labels: Awaiting Review

#50 add product to seller page
  seller/seller.html
  seller/seller.js
Labels: Done

#48 Add test instructions and tests
  assets/js/logic.js
  assets/js/logic.test.js
Labels: Done

#52 Add Products to Cart and test
  assets/css/style.css
  assets/js/dom.js
  assets/js/logic.js
  assets/js/logic.test.js
Labels: Done

#54 Grid and list preview
  assets/css/style.css
  assets/js/dom.js
  index.html
Labels: Awaiting Review

#55 Resolved conflict
  assets/js/dom.js
Labels: Awaiting Review

#58 Fix Grid Button Bug
  assets/css/style.css
  assets/js/dom.js
  index.html
Labels: Awaiting Review

#60 create edit and delete to seller page
  assets/css/style.css
  seller/seller.css
  seller/seller.html
  seller/seller.js
Labels: Done

#62 add test to seller bage
  assets/js/logic.js
  assets/js/logic.test.js
  seller/seller.js
Labels: Awaiting Review

#64 Add Css Styling
  assets/css/style.css
  assets/js/dom.js
  cart/cart.html
  index.html
  seller/seller.html
Labels: Awaiting Review

#67 delete product from seller page
  assets/css/style.css
  seller/seller.html
  seller/seller.js
Labels: Awaiting Review

#68 Update README.md
  README.md
Labels: Awaiting Review

#69 Edit product in seller page
  assets/css/style.css
  seller/seller.html
  seller/seller.js
Labels: Awaiting Review

#71 Fix total price bug
  assets/js/cart.js
  assets/js/dom.js
  cart/cart.html
Labels: Awaiting Review, Done

#76 edit card page
  cart/cart.html
  package.json
Labels: Awaiting Review
